azure_openai:
  api_type: "azure"
  api_key: "your_api_key"
  api_base: "your_api_base_url" # e.g. "https://vietgpt.openai.azure.com/"
  api_version: "your_api_version" # e.g. "2024-02-15-preview"
  deployment_name: "your_deployment_name" # e.g. "gpt-4o-2024-11-20"

